language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    #Cypress cache
    - ~/.cache

install:
  - npm ci

script:
  - npm start & wait-on http://localhost:3000
  - cypress run --record --key f3485b7b-fc97-462d-ba5f-7d93876c3c3e
  - npm run build

deploy:
  provider: surge
  project: ./build/
  domain: ca3frontendteam2.surge.sh
  skip_cleanup: true
