language: node_js
node_js:
  - lts/*

cache:
  npm: true
  directories:
    #Cypress cache
    - ~/.cache

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: surge
  project: ./build/
  domain: ca3frontendteam2.surge.sh
  deploy.skip_cleanup: true
